name: LepsiMisto
description: A sample Polymer application
dependencies:
    polymer: ">=0.15.1+3 <0.16.0"
    paper_elements: ">=0.5.0 <0.6.0"
    core_elements: ">=0.4.0+2 <0.5.0"
transformers:
- polymer:
    entry_points: web/lepsimisto.html
